### PR TITLE
Add label-wrap feature

### PR DESCRIPTION
**Pull request by feluelle**

### CODE REVIEW

**Comment by feluelle** [comment]
@nathadfield this feature could be interesting for you. You could set `--label-wrap` to either a number or a separator to wrap the labels to new lines.

**Comment by nathadfield** [comment]
@feluelle Definitely!  Happy to give it a try when it's a available.

**Comment by feluelle** [comment]
It is now available in `1.1.0rc1`. I would really appreciate if you could test it. :)

**Comment by nathadfield** [comment]
Much better!

Screenshot 2022-01-27 at 13 58 22

**Pull request merged**
